export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const USER_LOADED = "USER_LOADED"

export const CUSTOMER_LOAD_SUCCESS = "CUSTOMER_LOAD_SUCCESS"
export const CUSTOMER_LOAD_FAILED = "CUSTOMER_LOAD_FAILED"

export const PRODUCT_LOAD_SUCCESS = "PRODUCT_LOAD_SUCCESS"
export const PRODUCT_LOAD_FAILED = "PRODUCT_LOAD_FAILED"

export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD__SUCCESS"
export const PRODUCT_ADD_FAILED = "PRODUCT_ADD_FAILED"

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED"

export const MY_ORDER_DETAILS_REQUEST = "MY_ORDER_DETAILS_REQUEST"
export const MY_ORDER_DETAILS_SUCCESS = "MY_ORDER_DETAILS_SUCCESS"
export const MY_ORDER_DETAILS_FAILED = "MY_ORDER_DETAILS_FAILED"

export const MODIFY_ORDER_REQUEST = "MODIFY_ORDER_REQUEST"
export const MODIFY_ORDER_SUCCESS = "MODIFY_ORDER_SUCCESS"
export const MODIFY_ORDER_FAILED = "MODIFY_ORDER_FAILED"
