export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const USER_LOADED = "USER_LOADED"

export const CUSTOMER_LOAD_SUCCESS = "CUSTOMER_LOAD_SUCCESS"
export const CUSTOMER_LOAD_FAILED = "CUSTOMER_LOAD_FAILED"

export const PRODUCT_LOAD_SUCCESS = "PRODUCT_LOAD_SUCCESS"
export const PRODUCT_LOAD_FAILED = "PRODUCT_LOAD_FAILED"

export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD__SUCCESS"
export const PRODUCT_ADD_FAILED = "PRODUCT_ADD_FAILED"

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED"
